#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "vert"
name = "Vert"
description.en = "File conversion utility"
description.fr = "Utilitaire de conversion de fichiers"

version = "2026.02.05~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://vert.sh/"
demo = "https://vert.sh/"
code = "https://github.com/VERT-sh/VERT"
fund = "https://donations.vert.sh"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "amd64"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/VERT-sh/VERT/archive/897ae567027f326e6a605808981e74c0e897ef70.tar.gz"
    sha256 = "fe882e78ccce8740501c8d90efcdf6be9b6fea7679bd4fc2c3a213020ff7c4e1"
    
    autoupdate.upstream = "https://github.com/VERT-sh/VERT"
    autoupdate.strategy = "latest_github_commit"

    [resources.sources.vertd]
    rename = "vertd"
    in_subdir = false
    extract = false
    url = "https://github.com/VERT-sh/vertd/releases/download/nightly-8abb761889d3138f5b91401a533bc7e7211a99ff/vertd-linux-x86_64"
    sha256 = "75d7d23ea65b0b5cbbecbfb5dc50a0cdf35543a2f81e40f99f2211f2c1031853"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/VERT-sh/vertd"
    autoupdate.asset.amd64 = "vertd-linux-x86_64"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg"

    [resources.ports]
    main.default = 24153

    [resources.nodejs]
    version = "22"
