#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "vert"
name = "Vert"
description.en = "File conversion utility"
description.fr = "Utilitaire de conversion de fichiers"

version = "2026.02.05~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://vert.sh/"
demo = "https://vert.sh/"
code = "https://github.com/VERT-sh/VERT"
fund = "https://donations.vert.sh"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ['amd64']
multi_instance = true

ldap = false
sso = false

disk = "2100M"
ram.build = "2300M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/VERT-sh/VERT/archive/897ae567027f326e6a605808981e74c0e897ef70.tar.gz"
    sha256 = "fe882e78ccce8740501c8d90efcdf6be9b6fea7679bd4fc2c3a213020ff7c4e1"
    
    autoupdate.upstream = "https://github.com/VERT-sh/VERT"
    autoupdate.strategy = "latest_github_commit"

    [resources.sources.vertd_prebuilt]
    rename = "vertd"
    in_subdir = false
    extract = false
    amd64.url = "https://github.com/VERT-sh/vertd/releases/download/nightly-8abb761889d3138f5b91401a533bc7e7211a99ff/vertd-linux-x86_64"
    amd64.sha256 = "75d7d23ea65b0b5cbbecbfb5dc50a0cdf35543a2f81e40f99f2211f2c1031853"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/VERT-sh/vertd"
    autoupdate.asset.amd64 = "vertd-linux-x86_64"

    [resources.sources.vertd_source]
    in_subdir = true
    extract = true
    amd64.url = "https://github.com/VERT-sh/vertd/archive/ed746da8c0368afbdd3c4ad3cf74bc683efb3666.tar.gz"
    amd64.sha256 = "92956d6b9ba3e5d9126338d7b593314a98723aed7da46df6fd43b656f24dbe9b"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg, pkgconf, libssl-dev"

    [resources.ports]

    [resources.nodejs]
    version = "22"
