#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "vert"
name = "Vert"
description.en = "File conversion utility"
description.fr = "Utilitaire de conversion de fichiers"

version = "2026.01.02~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://vert.sh/"
demo = "https://vert.sh/"
code = "https://github.com/VERT-sh/VERT"
fund = "https://donations.vert.sh"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/VERT-sh/VERT/archive/838a6c7e0bd70e6dfdcac9c833c968291eeefdf9.tar.gz"
    sha256 = "fdeff31854168dbde2308eaf2221ea8090c3177cc675c12bd1a346fcbe53ab26"
    
    autoupdate.upstream = "https://github.com/VERT-sh/VERT"
    autoupdate.strategy = "latest_github_commit"

    [resources.sources.vertd]
    rename = "vertd"
    in_subdir = false
    extract = false
    url = "https://github.com/VERT-sh/vertd/archive/refs/tags/1.0.tar.gz"
    sha256 = "f3bac3ca102d557d7dbb6aa4f2b84ac524700c82c2d47c686a6b448d07261f2c"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/VERT-sh/vertd"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg"

    [resources.ports]
    main.default = 24153

    [resources.nodejs]
    version = "22"
